---
name: App-ZofCMS-Plugin-ImageResize
version: 0.0103
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: Plugin to resize images
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  App::ZofCMS::Plugin::Base: 0.0103
  File::Copy: 2.11
  File::Spec: 3.3
  Image::Resize: 0.5
  Image::Size: 3.2
configure_requires:
  Module::Build: 0.34
provides:
  App::ZofCMS::Plugin::ImageResize:
    file: lib/App/ZofCMS/Plugin/ImageResize.pm
    version: 0.0103
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
